[features]
seeds = false
skip-lint = false
[programs.localnet]
staking_program = "EKqX4UHZW8LjUpyte77f6U1TydESn2dJQb6NGA91UBin"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/agathokako/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
